In [1]:
import pandas as pd
import numpy as np
from normalize_countries import normalize_team_name

In [2]:
df = pd.read_csv("dados/confrontos/historico_confrontos.csv")
display(df.head())

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [3]:
df = df.drop(columns=["tournament","city","country","neutral"])

In [4]:
from datetime import date

def convert_data_string(data_string: str):
    year, month, day = list(map(int, data_string.split("-")))
    return date(year,month,day)

df["date"] = df["date"].apply(convert_data_string)

display(df.head())

         date home_team away_team  home_score  away_score
0  1872-11-30  Scotland   England         0.0         0.0
1  1873-03-08   England  Scotland         4.0         2.0
2  1874-03-07  Scotland   England         2.0         1.0
3  1875-03-06   England  Scotland         2.0         2.0
4  1876-03-04  Scotland   England         3.0         0.0

In [5]:
fim_copa_22 = date(year=2022,month=12, day=18)
inicio_copa26 = date(year=2026,month=6,day=11)
df_ciclo26 = df[(df["date"] > fim_copa_22) & (df["date"] < inicio_copa26)]

display(df_ciclo26)

             date    home_team    away_team  home_score  away_score
45787  2022-12-20     Cambodia  Philippines         3.0         2.0
45788  2022-12-20       Brunei     Thailand         0.0         5.0
45789  2022-12-21      Myanmar     Malaysia         0.0         1.0
45790  2022-12-21         Laos      Vietnam         0.0         6.0
45791  2022-12-23         Oman        Syria         2.0         1.0
...           ...          ...          ...         ...         ...
49400  2026-06-09         Iraq    Venezuela         0.0         2.0
49401  2026-06-10      Bolivia      Algeria         0.0         4.0
49402  2026-06-10      England   Costa Rica         3.0         0.0
49403  2026-06-10     Portugal      Nigeria         2.0         1.0
49404  2026-06-10  Afghanistan     Pakistan         0.0         2.0

[3618 rows x 5 columns]

In [6]:
qualified_teams = [
    "Canada",
    "United States",
    "Mexico",
    "Curacao",
    "Haiti",
    "Panama",
    "Japan",
    "Iran",
    "Uzbekistan",
    "South Korea",
    "Jordan",
    "Australia",
    "Qatar",
    "Saudi Arabia",
    "New Zealand",
    "Argentina",
    "Brazil",
    "Ecuador",
    "Uruguay",
    "Colombia",
    "Paraguay",
    "Morocco",
    "Tunisia",
    "Egypt",
    "Algeria",
    "Ghana",
    "Cape Verde",
    "South Africa",
    "Ivory Coast",
    "Senegal",
    "England",
    "France",
    "Croatia",
    "Portugal",
    "Norway",
    "Netherlands",
    "Germany",
    "Switzerland",
    "Austria",
    "Belgium",
    "Spain",
    "Scotland",
    "Turkey",
    "Czech Republic",
    "Sweden",
    "Bosnia and Herzegovina",
    "DR Congo",
    "Iraq"
]

df_ciclo26 = df_ciclo26[(df_ciclo26["home_team"].isin(qualified_teams)) | (df_ciclo26["away_team"].isin(qualified_teams))]
df_ciclo26 = df_ciclo26.reset_index(drop=True)
df_ciclo26.head()

         date home_team     away_team  home_score  away_score
0  2022-12-30      Iraq        Kuwait         1.0         0.0
1  2023-01-06      Iraq          Oman         0.0         0.0
2  2023-01-06     Yemen  Saudi Arabia         0.0         2.0
3  2023-01-07    Kuwait         Qatar         0.0         2.0
4  2023-01-09    Sweden       Finland         2.0         0.0

In [7]:
print(df_ciclo26.shape)

(1576, 5)

In [8]:
display(df_ciclo26)

            date     home_team     away_team  home_score  away_score
0     2022-12-30          Iraq        Kuwait         1.0         0.0
1     2023-01-06          Iraq          Oman         0.0         0.0
2     2023-01-06         Yemen  Saudi Arabia         0.0         2.0
3     2023-01-07        Kuwait         Qatar         0.0         2.0
4     2023-01-09        Sweden       Finland         2.0         0.0
...          ...           ...           ...         ...         ...
1571  2026-06-09  Saudi Arabia       Senegal         0.0         0.0
1572  2026-06-09          Iraq     Venezuela         0.0         2.0
1573  2026-06-10       Bolivia       Algeria         0.0         4.0
1574  2026-06-10       England    Costa Rica         3.0         0.0
1575  2026-06-10      Portugal       Nigeria         2.0         1.0

[1576 rows x 5 columns]

In [9]:
df_ciclo26.to_csv("dados/confrontos/historico_confrontos_ciclo2026.csv")

"""obs: definimos ciclo todos os jogos de seleções entre a ocorrência de duas copas!"""

"""Desta parte para cima, é a criação manual do histórico de jogos do ciclo de 22-26, devido o período irregular
da copa de 2022.Agora começarão a ser implementadas funções que analisam de forma geral os jogos antes do ciclo 22-26."""

#Anos das copas, menos os que ocorreram durante a ww2
anos_copa = [i for i in range(1930,2027,4)]
anos_copa.remove(1946)
anos_copa.remove(1942)

In [10]:
import os

df_todos_jogos = pd.read_csv("dados/confrontos/historico_confrontos.csv")

df_todos_jogos['date'] = pd.to_datetime(df_todos_jogos['date'])

os.makedirs("dados/confrontos", exist_ok=True)

def separar_jogos_por_ciclo(ano):
    """
    Filtra todos os jogos do mundo que ocorreram no intervalo de 4 anos 
    antes da Copa especificada.
    Utiliza dados de todos os jogos que ocorreram no ciclo.
    """
    
    if ano == 1930:
        data_inicio = pd.to_datetime("1926-08-01")
        data_fim = pd.to_datetime("1930-06-30")
        
    elif ano == 1950:
        data_inicio = pd.to_datetime("1946-08-01")
        data_fim = pd.to_datetime("1950-05-31")
        
    elif ano == 2022:
        data_inicio = pd.to_datetime("2018-08-01")
        data_fim = pd.to_datetime("2022-10-31")

    elif ano == 2026:
        data_inicio = pd.to_datetime("2023-01-01")
        data_fim = pd.to_datetime("2026-06-10")
        
    else:
        data_inicio = pd.to_datetime(f"{ano-4}-08-01")
        data_fim = pd.to_datetime(f"{ano}-05-28")
        
    mask = (df_todos_jogos['date'] >= data_inicio) & (df_todos_jogos['date'] <= data_fim)
    df_ciclo = df_todos_jogos[mask].copy()

    df_ciclo["resultado"] = np.where(
        df_ciclo["home_score"] > df_ciclo["away_score"], 1, 
        np.where(df_ciclo["away_score"] > df_ciclo["home_score"], 2, 0)  
    )
    #!!!!!
    # 1 = Time da casa venceu ; 2 = Time de fora venceu ; 0 = Empate
    
    caminho_saida = f"dados/confrontos/historico_confrontos_ciclo{ano}.csv"
    df_ciclo.to_csv(caminho_saida, index=False)
    
    print(f"Ciclo {ano}: {len(df_ciclo)} jogos salvos (De {data_inicio.date()} até {data_fim.date()})")

# Executar a função para todos os anos
#print("Iniciando a separação dos ciclos...")
#for ano in anos_copa:
    #separar_jogos_por_ciclo(ano)
#print("Separação concluída!")

In [11]:
def cicle_games(df, ano_copa):

    """
    Filtra todas os jogos por ciclo, porém apenas jogos que alguma seleção classificada para
    a copa jogou.
    """

    if ano_copa != 2022 and ano_copa != 2026:
        inicio_ciclo = date(year=ano_copa-4, month=8, day=1)
        fim_ciclo = date(year=ano_copa, month=5, day=26)
    
    elif ano_copa == 2022:
        inicio_ciclo = date(year=ano_copa-4, month=8, day=1)
        fim_ciclo = date(year=ano_copa, month=11, day=19)

    elif ano_copa == 2026:
        inicio_ciclo = date(year=ano_copa-4, month=12, day=20)
        fim_ciclo = date(year=ano_copa, month=6, day=10)

    selecoes = pd.read_csv(f'dados/copas/FIFA - {ano_copa}.csv')
    selecoes = selecoes['Team']
    jogos = df
    df_ciclo = jogos[(jogos['date'] >= inicio_ciclo) & (jogos['date'] <= fim_ciclo)]
    df_ciclo = df_ciclo[(df_ciclo['home_team'].isin(selecoes)) | (df_ciclo['away_team'].isin(selecoes))]
    df_ciclo["resultado"] = np.where(
        df_ciclo["home_score"] > df_ciclo["away_score"], 1, 
        np.where(df_ciclo["away_score"] > df_ciclo["home_score"], 2, 0)  
    )
    #!!!!!
    # 1 = Time da casa venceu ; 2 = Time de fora venceu ; 0 = Empate
    df_ciclo = df_ciclo.reset_index()
    df_ciclo.to_csv(f"dados/confrontos/historico_confrontos_ciclo{ano_copa}.csv")

for ano in anos_copa:
    try:
        cicle_games(df, ano)
    except: ...

In [ ]:
def stats_cicle(ano):
    """
    Gera tabelas de classificação baseadas nos jogos do ciclo, contando vitórias, derrotas, empates,
    e pontuando as seleções.
    """
    if ano == 2026:
        teams = [normalize_team_name(t) for t in qualified_teams]
    else:
        teams = list(set(pd.read_csv(f"dados/copas/FIFA - {ano}.csv")["Team"]))
        teams = [normalize_team_name(t) for t in teams]

    df_confrontos = pd.read_csv(f"dados/confrontos/historico_confrontos_ciclo{ano}.csv")
    all_teams = pd.concat([df_confrontos['home_team'], df_confrontos['away_team']]).unique()
    mapa_nomes = {team: normalize_team_name(team) for team in all_teams}
    
    df_confrontos['home_team'] = df_confrontos['home_team'].map(mapa_nomes)
    df_confrontos['away_team'] = df_confrontos['away_team'].map(mapa_nomes)

    print(len(teams))
    print(teams)

    df_stats = pd.DataFrame({"team": teams})
    df_stats = df_stats.set_index("team")
    df_stats["wins"] = 0
    df_stats["draws"] = 0
    df_stats["loses"] = 0
    df_stats["points"] = 0
    df_stats["games_played"] = 0
    df_stats["goals_for"] = 0
    df_stats["goals_against"] = 0

    for row in df_confrontos.itertuples():
        home = row.home_team
        away = row.away_team
        home_score, away_score = row.home_score, row.away_score

        # só soma se o time estiver na lista da Copa
        is_home_qualified = home in df_stats.index
        is_away_qualified = away in df_stats.index

        if is_home_qualified: 
            df_stats.at[home, "games_played"] += 1
            df_stats.at[home, "goals_for"] += home_score     
            df_stats.at[home, "goals_against"] += away_score

        if is_away_qualified: 
            df_stats.at[away, "games_played"] += 1
            df_stats.at[away, "goals_for"] += away_score    
            df_stats.at[away, "goals_against"] += home_score
        
        if home_score > away_score:
            if is_home_qualified: df_stats.at[home, "wins"] += 1
            if is_away_qualified: df_stats.at[away, "loses"] += 1

        elif away_score > home_score:
            if is_home_qualified: df_stats.at[home, "loses"] += 1
            if is_away_qualified: df_stats.at[away, "wins"] += 1
            
        else:
            if is_home_qualified: df_stats.at[home, "draws"] += 1
            if is_away_qualified: df_stats.at[away, "draws"] += 1

    df_stats["goal_difference"] = df_stats["goals_for"] - df_stats["goals_against"]
    df_stats["goal_diff_per_game"] = round(df_stats["goal_difference"] / df_stats["games_played"], 2)
    df_stats["points"] = df_stats["wins"]*3 + df_stats["draws"]
    df_stats["points_per_game"] = round(df_stats["points"] / df_stats["games_played"],2)
    df_stats = df_stats.sort_values(by="points", ascending=False)
    df_stats.to_csv(f"dados/estatisticas_ciclos/estatisticas_ciclo{ano}.csv")

for ano in anos_copa:
    stats_cicle(ano)

13
['Uruguay', 'Yugoslavia', 'Chile', 'Brazil', 'United States', 'Peru', 'Belgium', 'Mexico', 'Argentina', 'Bolivia, Plurinational State of', 'Romania', 'France', 'Paraguay']
16
['Switzerland', 'Egypt', 'Sweden', 'Brazil', 'Italy', 'Hungary', 'Netherlands', 'United States', 'Belgium', 'Argentina', 'Austria', 'Germany', 'Czechoslovakia', 'Spain', 'France', 'Romania']
15
['Brazil', 'Switzerland', 'Sweden', 'Poland', 'Italy', 'Norway', 'Hungary', 'Netherlands', 'Dutch East Indies', 'Belgium', 'Germany', 'Czechoslovakia', 'Romania', 'France', 'Cuba']
13
['Uruguay', 'Yugoslavia', 'Sweden', 'Brazil', 'Switzerland', 'Italy', 'Chile', 'United States', 'Mexico', 'Bolivia, Plurinational State of', 'England', 'Spain', 'Paraguay']
16
['Uruguay', 'Switzerland', 'Brazil', 'Yugoslavia', 'South Korea', 'Italy', 'Scotland', 'Hungary', 'Belgium', 'Mexico', 'Austria', 'England', 'Czechoslovakia', 'Turkey', 'France', 'Germany']
16
['Brazil', 'Yugoslavia', 'Sweden', 'Hungary', 'Soviet Union', 'Paraguay', 'Mexico', 'Argentina', 'Northern Ireland', 'England', 'Austria', 'Czechoslovakia', 'Scotland', 'France', 'Wales', 'Germany']
16
['Brazil', 'Yugoslavia', 'Chile', 'Uruguay', 'Switzerland', 'Italy', 'Hungary', 'Soviet Union', 'Mexico', 'Argentina', 'Colombia', 'England', 'Bulgaria', 'Czechoslovakia', 'Spain', 'Germany']
16
['Uruguay', 'Brazil', 'Chile', 'Switzerland', 'Italy', 'Hungary', 'Soviet Union', 'North Korea', 'Portugal', 'Mexico', 'Argentina', 'England', 'Bulgaria', 'Spain', 'France', 'Germany']
16
['Brazil', 'Uruguay', 'Sweden', 'El Salvador', 'Italy', 'Soviet Union', 'Bulgaria', 'Peru', 'Belgium', 'Mexico', 'Israel', 'England', 'Czechoslovakia', 'Romania', 'Morocco', 'Germany']
16
['Brazil', 'Poland', 'Sweden', 'Yugoslavia', 'Chile', 'East Germany', 'Italy', 'Uruguay', 'Haiti', 'Netherlands', 'Argentina', 'Bulgaria', 'Australia', 'Scotland', 'Angola', 'Germany']
16
['Brazil', 'Poland', 'Sweden', 'Italy', 'Scotland', 'Tunisia', 'Hungary', 'Netherlands', 'Peru', 'Mexico', 'Argentina', 'Austria', 'Spain', 'France', 'Iran', 'Germany']
24
['Poland', 'Yugoslavia', 'Chile', 'Czechoslovakia', 'Algeria', 'El Salvador', 'New Zealand', 'Italy', 'Soviet Union', 'Peru', 'Kuwait', 'Northern Ireland', 'Honduras', 'Scotland', 'Spain', 'Hungary', 'Cameroon', 'Argentina', 'Brazil', 'Belgium', 'England', 'Austria', 'France', 'Germany']
24
['Uruguay', 'Poland', 'Iraq', 'Algeria', 'Italy', 'Denmark', 'Soviet Union', 'Northern Ireland', 'Scotland', 'Spain', 'Paraguay', 'South Korea', 'Hungary', 'Portugal', 'Mexico', 'Argentina', 'Bulgaria', 'Morocco', 'Brazil', 'Belgium', 'Canada', 'England', 'France', 'Germany']
24
['Uruguay', 'Yugoslavia', 'Sweden', 'Czechoslovakia', 'Ireland', 'Italy', 'Soviet Union', 'Scotland', 'Spain', 'Romania', 'South Korea', 'Cameroon', 'Netherlands', 'United States', 'Argentina', 'Colombia', 'United Arab Emirates', 'Brazil', 'Egypt', 'Belgium', 'Costa Rica', 'England', 'Austria', 'Germany']
24
['Sweden', 'Nigeria', 'Ireland', 'Italy', 'Norway', 'Romania', 'Spain', 'South Korea', 'Cameroon', 'Netherlands', 'Saudi Arabia', 'United States', 'Mexico', 'Argentina', 'Colombia', 'Bulgaria', 'Morocco', 'Greece', 'Brazil', 'Switzerland', 'Belgium', 'Bolivia, Plurinational State of', 'Russian Federation', 'Germany']
32
['Chile', 'Nigeria', 'South Africa', 'Iran', 'Italy', 'Norway', 'Denmark', 'Spain', 'Romania', 'Paraguay', 'Scotland', 'Croatia', 'South Korea', 'Tunisia', 'Cameroon', 'Netherlands', 'Saudi Arabia', 'United States', 'Mexico', 'Argentina', 'Colombia', 'Jamaica', 'Yugoslavia', 'Bulgaria', 'Morocco', 'Brazil', 'Japan', 'Belgium', 'England', 'Austria', 'Germany', 'France']
32
['Uruguay', 'Poland', 'Sweden', 'Nigeria', 'South Africa', 'Ecuador', 'Ireland', 'Italy', 'Denmark', 'Turkey', 'Spain', 'Paraguay', 'Croatia', 'South Korea', 'Tunisia', 'Senegal', 'Cameroon', 'United States', 'Saudi Arabia', 'Portugal', 'Mexico', 'Argentina', 'Brazil', 'Japan', 'Belgium', 'Costa Rica', 'Slovenia', 'England', 'Russian Federation', 'Germany', 'China', 'France']
32
['Poland', 'Sweden', 'Ukraine', 'Czechia', 'Serbia and Montenegro', 'Ecuador', 'Iran', 'Italy', 'Togo', 'Australia', 'Spain', 'Paraguay', 'Croatia', 'South Korea', 'Ghana', 'Tunisia', 'Netherlands', 'United States', 'Saudi Arabia', 'Portugal', 'Mexico', 'Argentina', 'Trinidad and Tobago', 'Brazil', 'Switzerland', 'Japan', 'Angola', 'Costa Rica', 'England', 'Germany', 'France', 'Ivory Coast']
32
['Uruguay', 'Chile', 'Nigeria', 'Serbia', 'South Africa', 'Algeria', 'New Zealand', 'Italy', 'Denmark', 'North Korea', 'Australia', 'Spain', 'Honduras', 'Paraguay', 'South Korea', 'Ghana', 'Cameroon', 'Netherlands', 'United States', 'Slovakia', 'Portugal', 'Mexico', 'Argentina', 'Greece', 'Brazil', 'Switzerland', 'Japan', 'Slovenia', 'England', 'Germany', 'France', 'Ivory Coast']
32
['Uruguay', 'Chile', 'Nigeria', 'Ecuador', 'Iran', 'Algeria', 'Italy', 'Bosnia and Herzegovina', 'Australia', 'Spain', 'Honduras', 'Croatia', 'South Korea', 'Ghana', 'Cameroon', 'Netherlands', 'United States', 'Portugal', 'Mexico', 'Colombia', 'Argentina', 'Greece', 'Brazil', 'Switzerland', 'Japan', 'Belgium', 'Costa Rica', 'England', 'Russian Federation', 'Germany', 'France', 'Ivory Coast']
32
['Uruguay', 'Poland', 'Sweden', 'Nigeria', 'Serbia', 'Iran', 'Denmark', 'Panama', 'Peru', 'Australia', 'Spain', 'Croatia', 'South Korea', 'Tunisia', 'Senegal', 'Saudi Arabia', 'Portugal', 'Mexico', 'Colombia', 'Argentina', 'Morocco', 'Brazil', 'Switzerland', 'Japan', 'Egypt', 'Belgium', 'Costa Rica', 'England', 'Russian Federation', 'Germany', 'France', 'Iceland']
32
['Uruguay', 'Poland', 'Serbia', 'Ecuador', 'Iran', 'Denmark', 'Australia', 'Spain', 'Wales', 'Croatia', 'South Korea', 'Ghana', 'Tunisia', 'Senegal', 'Cameroon', 'Netherlands', 'United States', 'Saudi Arabia', 'Portugal', 'Mexico', 'Argentina', 'Morocco', 'Brazil', 'Switzerland', 'Japan', 'Belgium', 'Canada', 'Costa Rica', 'England', 'Qatar', 'Germany', 'France']
48
['Canada', 'United States', 'Mexico', 'Netherlands', 'Haiti', 'Panama', 'Japan', 'Iran', 'Uzbekistan', 'South Korea', 'Jordan', 'Australia', 'Qatar', 'Saudi Arabia', 'New Zealand', 'Argentina', 'Brazil', 'Ecuador', 'Uruguay', 'Colombia', 'Paraguay', 'Morocco', 'Tunisia', 'Egypt', 'Algeria', 'Ghana', 'Cape Verde', 'South Africa', 'Ivory Coast', 'Senegal', 'England', 'France', 'Croatia', 'Portugal', 'Norway', 'Netherlands', 'Germany', 'Switzerland', 'Austria', 'Belgium', 'Spain', 'Scotland', 'Turkey', 'Czechia', 'Sweden', 'Bosnia and Herzegovina', 'Congo', 'Iraq']

In [ ]:
#Separando os confrontos de cada copa

df_confrontos_copas = pd.read_csv("dados/confrontos_copas/WorldCupMatches.csv")
for ano in anos_copa:
    df_confrontos_copa = df_confrontos_copas[df_confrontos_copas["Year"] == ano].copy()
    
    df_confrontos_copa["Home Team Name"] = df_confrontos_copa["Home Team Name"].apply(normalize_team_name)
    df_confrontos_copa["Away Team Name"] = df_confrontos_copa["Away Team Name"].apply(normalize_team_name)
    
    df_confrontos_copa["resultado"] = np.where(
        df_confrontos_copa["Home Team Goals"] > df_confrontos_copa["Away Team Goals"], 1, 
        np.where(df_confrontos_copa["Away Team Goals"] > df_confrontos_copa["Home Team Goals"], 2, 0)  
    )
    #display(df_confrontos_copa)
    df_confrontos_copa = df_confrontos_copa.reset_index(drop=True)
    df_confrontos_copa.to_csv(f"dados/confrontos_copas/confrontos{ano}.csv")

In [ ]:
#Separando os csv que serão usados para treinar o modelo!


for ano in anos_copa:
    df_confrontos = pd.read_csv(f"dados/confrontos_copas/confrontos{ano}.csv")
    df_ciclo = pd.read_csv(f"dados/estatisticas_ciclos/estatisticas_ciclo{ano}.csv")
    
    df_ciclo["team"] = df_ciclo["team"].apply(normalize_team_name)
    df_ciclo = df_ciclo.set_index("team")
    
    df_input_modelo = pd.DataFrame()

    wins_difference = []
    draws_difference = []
    loses_difference = []
    points_per_game_difference = []
    goal_diff_pg_difference = []
    allign_results = []

    df_ciclo["win_rate"] = (df_ciclo["wins"] / df_ciclo["games_played"]).fillna(0)
    df_ciclo["draw_rate"] = (df_ciclo["draws"] / df_ciclo["games_played"]).fillna(0)
    df_ciclo["lose_rate"] = (df_ciclo["loses"] / df_ciclo["games_played"]).fillna(0)

    # Padroniza todas as colunas: minúsculas e com '_' no lugar do espaço
    df_confrontos.columns = df_confrontos.columns.str.lower().str.replace(' ', '_')

    unmatched_teams = set()
    for row in df_confrontos.itertuples():
        home = normalize_team_name(row.home_team_name)
        away = normalize_team_name(row.away_team_name)
        if home not in df_ciclo.index:
            unmatched_teams.add(home)
        if away not in df_ciclo.index:
            unmatched_teams.add(away)
    
    if unmatched_teams:
        print(f"Aviso Ano {ano}: Seleções não encontradas em estatísticas: {unmatched_teams}")

    for row in df_confrontos.itertuples():
        home_team = normalize_team_name(row.home_team_name)
        away_team = normalize_team_name(row.away_team_name)
        
        # Pular linhas com equipes não mapeadas
        if home_team not in df_ciclo.index or away_team not in df_ciclo.index:
            continue

        wins_difference.append(df_ciclo.loc[home_team]["win_rate"] - df_ciclo.loc[away_team]["win_rate"])
        draws_difference.append(df_ciclo.loc[home_team]["draw_rate"] - df_ciclo.loc[away_team]["draw_rate"])
        loses_difference.append(df_ciclo.loc[home_team]["lose_rate"] - df_ciclo.loc[away_team]["lose_rate"])
        points_per_game_difference.append(df_ciclo.loc[home_team]["points_per_game"] - df_ciclo.loc[away_team]["points_per_game"])
        goal_diff_pg_difference.append(df_ciclo.loc[home_team]["goal_diff_per_game"] - df_ciclo.loc[away_team]["goal_diff_per_game"])
        allign_results.append(row.resultado)
    
    df_input_modelo["wins_difference"] = wins_difference
    df_input_modelo["draws_difference"] = draws_difference
    df_input_modelo["loses_difference"] = loses_difference
    df_input_modelo["points_per_game_difference"] = points_per_game_difference
    df_input_modelo["result"] = allign_results
    df_input_modelo['goal_diff_pg_difference'] = goal_diff_pg_difference

    total_original = len(df_confrontos)
    total_processado = len(df_input_modelo)
    print(f"Ano {ano}: {total_processado} de {total_original} linhas processadas")
    df_input_modelo.to_csv(f"dados/dados_modelo/input_modelo{ano}.csv", index=False)

Ano 1930: 18 de 18 linhas processadas
Ano 1934: 17 de 17 linhas processadas
Ano 1938: 18 de 18 linhas processadas
Ano 1950: 22 de 22 linhas processadas
Ano 1954: 26 de 26 linhas processadas
Ano 1958: 35 de 35 linhas processadas
Ano 1962: 32 de 32 linhas processadas
Ano 1966: 32 de 32 linhas processadas
Ano 1970: 32 de 32 linhas processadas
Ano 1974: 38 de 38 linhas processadas
Ano 1978: 38 de 38 linhas processadas
Ano 1982: 52 de 52 linhas processadas
Ano 1986: 52 de 52 linhas processadas
Ano 1990: 52 de 52 linhas processadas
Ano 1994: 52 de 52 linhas processadas
Ano 1998: 64 de 64 linhas processadas
Ano 2002: 64 de 64 linhas processadas
Ano 2006: 64 de 64 linhas processadas
Ano 2010: 64 de 64 linhas processadas
Ano 2014: 80 de 80 linhas processadas
Ano 2018: 64 de 64 linhas processadas
Ano 2022: 64 de 64 linhas processadas