In [76]:
import pandas as pd

In [77]:
df = pd.read_csv("dados/confrontos/historico_confrontos.csv")
display(df.head())

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [78]:
df = df.drop(columns=["tournament","city","country","neutral"])

In [79]:
from datetime import date

def convert_data_string(data_string: str):
    year, month, day = list(map(int, data_string.split("-")))
    return date(year,month,day)

df["date"] = df["date"].apply(convert_data_string)

display(df.head())

         date home_team away_team  home_score  away_score
0  1872-11-30  Scotland   England         0.0         0.0
1  1873-03-08   England  Scotland         4.0         2.0
2  1874-03-07  Scotland   England         2.0         1.0
3  1875-03-06   England  Scotland         2.0         2.0
4  1876-03-04  Scotland   England         3.0         0.0

In [80]:
fim_copa_22 = date(year=2022,month=12, day=18)
inicio_copa26 = date(year=2026,month=6,day=11)
df_ciclo26 = df[(df["date"] > fim_copa_22) & (df["date"] < inicio_copa26)]

display(df_ciclo26)

             date    home_team    away_team  home_score  away_score
45787  2022-12-20     Cambodia  Philippines         3.0         2.0
45788  2022-12-20       Brunei     Thailand         0.0         5.0
45789  2022-12-21      Myanmar     Malaysia         0.0         1.0
45790  2022-12-21         Laos      Vietnam         0.0         6.0
45791  2022-12-23         Oman        Syria         2.0         1.0
...           ...          ...          ...         ...         ...
49400  2026-06-09         Iraq    Venezuela         0.0         2.0
49401  2026-06-10      Bolivia      Algeria         0.0         4.0
49402  2026-06-10      England   Costa Rica         3.0         0.0
49403  2026-06-10     Portugal      Nigeria         2.0         1.0
49404  2026-06-10  Afghanistan     Pakistan         0.0         2.0

[3618 rows x 5 columns]

In [81]:
qualified_teams = [
    "Canada",
    "United States",
    "Mexico",
    "Curacao",
    "Haiti",
    "Panama",
    "Japan",
    "Iran",
    "Uzbekistan",
    "South Korea",
    "Jordan",
    "Australia",
    "Qatar",
    "Saudi Arabia",
    "New Zealand",
    "Argentina",
    "Brazil",
    "Ecuador",
    "Uruguay",
    "Colombia",
    "Paraguay",
    "Morocco",
    "Tunisia",
    "Egypt",
    "Algeria",
    "Ghana",
    "Cape Verde",
    "South Africa",
    "Ivory Coast",
    "Senegal",
    "England",
    "France",
    "Croatia",
    "Portugal",
    "Norway",
    "Netherlands",
    "Germany",
    "Switzerland",
    "Austria",
    "Belgium",
    "Spain",
    "Scotland",
    "Turkey",
    "Czech Republic",
    "Sweden",
    "Bosnia and Herzegovina",
    "DR Congo",
    "Iraq"
]

df_ciclo26 = df_ciclo26[(df["home_team"].isin(qualified_teams)) | (df["away_score"].isin(qualified_teams))]

/tmp/ipykernel_22924/1833006246.py:52: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ciclo26 = df_ciclo26[(df["home_team"].isin(qualified_teams)) | (df["away_score"].isin(qualified_teams))]

In [82]:
print(df_ciclo26.shape)

(1091, 5)

In [83]:
display(df_ciclo26)

             date     home_team     away_team  home_score  away_score
45802  2022-12-30          Iraq        Kuwait         1.0         0.0
45811  2023-01-06          Iraq          Oman         0.0         0.0
45818  2023-01-09        Sweden       Finland         2.0         0.0
45820  2023-01-09          Iraq  Saudi Arabia         2.0         0.0
45823  2023-01-10         Qatar       Bahrain         1.0         2.0
...           ...           ...           ...         ...         ...
49386  2026-06-09      DR Congo         Chile         1.0         2.0
49392  2026-06-09  Saudi Arabia       Senegal         0.0         0.0
49400  2026-06-09          Iraq     Venezuela         0.0         2.0
49402  2026-06-10       England    Costa Rica         3.0         0.0
49403  2026-06-10      Portugal       Nigeria         2.0         1.0

[1091 rows x 5 columns]