In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("dados/confrontos/historico_confrontos.csv")
display(df.head())

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [10]:
df = df.drop(columns=["tournament","city","country","neutral"])

In [11]:
from datetime import date

def convert_data_string(data_string: str):
    year, month, day = list(map(int, data_string.split("-")))
    return date(year,month,day)

df["date"] = df["date"].apply(convert_data_string)

display(df.head())

         date home_team away_team  home_score  away_score
0  1872-11-30  Scotland   England         0.0         0.0
1  1873-03-08   England  Scotland         4.0         2.0
2  1874-03-07  Scotland   England         2.0         1.0
3  1875-03-06   England  Scotland         2.0         2.0
4  1876-03-04  Scotland   England         3.0         0.0

In [12]:
fim_copa_22 = date(year=2022,month=12, day=18)
inicio_copa26 = date(year=2026,month=6,day=11)
df_ciclo26 = df[(df["date"] > fim_copa_22) & (df["date"] < inicio_copa26)]

display(df_ciclo26)

             date    home_team    away_team  home_score  away_score
45787  2022-12-20     Cambodia  Philippines         3.0         2.0
45788  2022-12-20       Brunei     Thailand         0.0         5.0
45789  2022-12-21      Myanmar     Malaysia         0.0         1.0
45790  2022-12-21         Laos      Vietnam         0.0         6.0
45791  2022-12-23         Oman        Syria         2.0         1.0
...           ...          ...          ...         ...         ...
49400  2026-06-09         Iraq    Venezuela         0.0         2.0
49401  2026-06-10      Bolivia      Algeria         0.0         4.0
49402  2026-06-10      England   Costa Rica         3.0         0.0
49403  2026-06-10     Portugal      Nigeria         2.0         1.0
49404  2026-06-10  Afghanistan     Pakistan         0.0         2.0

[3618 rows x 5 columns]

In [21]:
qualified_teams = [
    "Canada",
    "United States",
    "Mexico",
    "Curacao",
    "Haiti",
    "Panama",
    "Japan",
    "Iran",
    "Uzbekistan",
    "South Korea",
    "Jordan",
    "Australia",
    "Qatar",
    "Saudi Arabia",
    "New Zealand",
    "Argentina",
    "Brazil",
    "Ecuador",
    "Uruguay",
    "Colombia",
    "Paraguay",
    "Morocco",
    "Tunisia",
    "Egypt",
    "Algeria",
    "Ghana",
    "Cape Verde",
    "South Africa",
    "Ivory Coast",
    "Senegal",
    "England",
    "France",
    "Croatia",
    "Portugal",
    "Norway",
    "Netherlands",
    "Germany",
    "Switzerland",
    "Austria",
    "Belgium",
    "Spain",
    "Scotland",
    "Turkey",
    "Czech Republic",
    "Sweden",
    "Bosnia and Herzegovina",
    "DR Congo",
    "Iraq"
]

df_ciclo26 = df_ciclo26[(df["home_team"].isin(qualified_teams)) | (df["away_score"].isin(qualified_teams))]
df_ciclo26 = df_ciclo26.reset_index()

/tmp/ipykernel_150653/3298589592.py:52: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_ciclo26 = df_ciclo26[(df["home_team"].isin(qualified_teams)) | (df["away_score"].isin(qualified_teams))]

In [14]:
print(df_ciclo26.shape)

(1091, 5)

In [15]:
display(df_ciclo26)

             date     home_team     away_team  home_score  away_score
45802  2022-12-30          Iraq        Kuwait         1.0         0.0
45811  2023-01-06          Iraq          Oman         0.0         0.0
45818  2023-01-09        Sweden       Finland         2.0         0.0
45820  2023-01-09          Iraq  Saudi Arabia         2.0         0.0
45823  2023-01-10         Qatar       Bahrain         1.0         2.0
...           ...           ...           ...         ...         ...
49386  2026-06-09      DR Congo         Chile         1.0         2.0
49392  2026-06-09  Saudi Arabia       Senegal         0.0         0.0
49400  2026-06-09          Iraq     Venezuela         0.0         2.0
49402  2026-06-10       England    Costa Rica         3.0         0.0
49403  2026-06-10      Portugal       Nigeria         2.0         1.0

[1091 rows x 5 columns]

In [22]:
df_ciclo26.to_csv("dados/confrontos/historico_confrontos_ciclo26.csv")

In [ ]:
def stats_cicle(df, ano):

    qualified_teams = pd.read_csv(f"dados/copas/FIFA - {ano}.csv")
    qualified_teams = list(qualified_teams["Team"])
    print(qualified_teams)

    df_stats = pd.DataFrame({"team": qualified_teams})
    df_stats = df_stats.set_index("team")
    df_stats["wins"] = 0
    df_stats["draws"] = 0
    df_stats["loses"] = 0
    df_stats["points"] = 0
    df_stats["games_played"] = 0

    for row in df.itertuples():
        home, away = row.home_team, row.away_team
        home_score, away_score = row.home_score, row.away_score

        if home in qualified_teams: df_stats.at[home, "games_played"] += 1
        if away in qualified_teams: df_stats.at[away, "games_played"] += 1
        
        if home_score > away_score:
            if home in qualified_teams: df_stats.at[home, "wins"] += 1
            if away in qualified_teams: df_stats.at[away, "loses"] += 1
            
        elif away_score > home_score:
            if home in qualified_teams: df_stats.at[home, "loses"] += 1
            if away in qualified_teams: df_stats.at[away, "wins"] += 1
            
        else:
            if home in qualified_teams: df_stats.at[home, "draws"] += 1
            if away in qualified_teams: df_stats.at[away, "draws"] += 1

    df_stats["points"] = df_stats["wins"]*3 + df_stats["draws"]
    df_stats["points_per_game"] = round(df_stats["points"] / df_stats["games_played"],2)
    df_stats = df_stats.sort_values(by="points", ascending=False)
    df_stats.to_csv(f"dados/estatisticas_ciclos/estatisticas_ciclo{ano}.csv")
    
stats_cicle(df, 2010)

['Spain', 'Netherlands', 'Germany', 'Uruguay', 'Argentina', 'Brazil', 'Ghana', 'Paraguay', 'Japan', 'Chile', 'Portugal', 'United States', 'England', 'Mexico', 'South Korea', 'Slovakia', 'Ivory Coast', 'Slovenia', 'Switzerland', 'South Africa', 'Australia', 'New Zealand', 'Serbia', 'Denmark', 'Greece', 'Italy', 'Nigeria', 'Algeria', 'France', 'Honduras', 'Cameroon', 'North Korea']

               wins  draws  loses  points  games_played  points_per_game
team
Brazil          672    219    171    2235          1062             2.10
England         625    261    207    2136          1093             1.95
Argentina       592    260    220    2036          1072             1.90
Germany         600    215    219    2015          1034             1.95
South Korea     539    254    217    1871          1010             1.85
Mexico          515    233    258    1778          1006             1.77
Italy           477    243    173    1674           893             1.87
France          477    198    263    1629           938             1.74
Spain           461    185    140    1568           786             1.99
Netherlands     453    201    228    1560           882             1.77
Uruguay         428    243    302    1527           973             1.57
Denmark         402    185    287    1391           874             1.59
Japan           390    168    235    1338           793             1.69
United States   352    163    278    1219           793             1.54
Portugal        349    162    187    1209           698             1.73
Switzerland     316    207    364    1155           887             1.30
Ivory Coast     326    164    149    1142           639             1.79
Chile           316    179    340    1127           835             1.35
Nigeria         311    192    158    1125           661             1.70
Ghana           311    178    185    1111           674             1.65
Paraguay        275    210    301    1035           786             1.32
Algeria         288    165    167    1029           620             1.66
Australia       297    125    162    1016           584             1.74
Cameroon        271    192    153    1005           616             1.63
Honduras        247    161    212     902           620             1.45
Greece          240    155    238     875           633             1.38
South Africa    215    147    121     792           483             1.64
New Zealand     172     76    171     592           419             1.41
North Korea     162    106    122     592           390             1.52
Serbia          155     89    104     554           348             1.59
Slovakia        149     86    132     533           367             1.45
Slovenia        114     86    117     428           317             1.35

In [ ]:
def cicle_games(df, ano_copa):
    #a função tá certa, mas para todos os dados ficarem certos tem que corrijir os csv e eu to com preguiça

    if ano_copa != 2022 and ano_copa != 2026:
        inicio_ciclo = date(year=ano_copa-4, month=8, day=1)
        fim_ciclo = date(year=ano_copa, month=5, day=26)
    
    elif ano_copa == 2022:
        inicio_ciclo = date(year=ano_copa-4, month=8, day=1)
        fim_ciclo = date(year=ano_copa, month=11, day=19)

    elif ano_copa == 2026:
        inicio_ciclo = date(year=ano_copa-4, month=12, day=20)
        fim_ciclo = date(year=ano_copa, month=6, day=10)

    selecoes = pd.read_csv(f'dados/copas/FIFA - {ano_copa}.csv')
    selecoes = selecoes['Team']
    jogos = df
    df_ciclo = jogos[(jogos['date'] >= inicio_ciclo) & (jogos['date'] <= fim_ciclo)]
    df_ciclo = df_ciclo[(df_ciclo['home_team'].isin(selecoes)) | (df_ciclo['away_team'].isin(selecoes))]
    df_ciclo = df_ciclo.reset_index()
    df_ciclo.to_csv(f"dados/confrontos/historico_confrontos_ciclo{str(ano_copa)[2:]}.csv")
    stats_cicle(df, ano_copa)

anos_copa = pd.read_csv("dados/copas/FIFA - World Cup Summary.csv")
anos_copa = anos_copa["YEAR"]

for ano in anos_copa:
    cicle_games(df, ano)

['Uruguay', 'Argentina', 'United States', 'Yugoslavia', 'Chile', 'Brazil', 'France', 'Romania', 'Paraguay', 'Peru', 'Belgium', 'Bolivia', 'Mexico']

               wins  draws  loses  points  games_played  points_per_game
team
Brazil          672    219    171    2235          1062             2.10
Argentina       592    260    220    2036          1072             1.90
Mexico          515    233    258    1778          1006             1.77
France          477    198    263    1629           938             1.74
Uruguay         428    243    302    1527           973             1.57
Belgium         382    184    290    1330           856             1.55
United States   352    163    278    1219           793             1.54
Romania         335    195    236    1200           766             1.57
Chile           316    179    340    1127           835             1.35
Paraguay        275    210    301    1035           786             1.32
Peru            231    176    307     869           714             1.22
Yugoslavia      223     98    162     767           483             1.59
Bolivia         119    119    296     476           534             0.89

['Italy', 'Czechoslovakia', 'Germany', 'Austria', 'Spain', 'Hungary', 'Switzerland', 'Sweden', 'Argentina', 'France', 'Netherlands', 'Romania', 'Egypt', 'Brazil', 'Belgium', 'United States']

                wins  draws  loses  points  games_played  points_per_game
team
Brazil           672    219    171    2235          1062             2.10
Argentina        592    260    220    2036          1072             1.90
Germany          600    215    219    2015          1034             1.95
Sweden           542    235    327    1861          1104             1.69
Italy            477    243    173    1674           893             1.87
Hungary          472    222    312    1638          1006             1.63
France           477    198    263    1629           938             1.74
Spain            461    185    140    1568           786             1.99
Netherlands      453    201    228    1560           882             1.77
Belgium          382    184    290    1330           856             1.55
Egypt            379    188    192    1325           759             1.75
Austria          367    187    309    1288           863             1.49
United States    352    163    278    1219           793             1.54
Romania          335    195    236    1200           766             1.57
Switzerland      316    207    364    1155           887             1.30
Czechoslovakia   236    119    165     827           520             1.59

['Italy', 'Hungary', 'Brazil', 'Sweden', 'Czechoslovakia', 'Switzerland', 'Cuba', 'France', 'Romania', 'Germany', 'Poland', 'Norway', 'Belgium', 'Netherlands', 'Dutch East Indies']

                   wins  draws  loses  points  games_played  points_per_game
team
Brazil              672    219    171    2235          1062             2.10
Germany             600    215    219    2015          1034             1.95
Sweden              542    235    327    1861          1104             1.69
Italy               477    243    173    1674           893             1.87
Hungary             472    222    312    1638          1006             1.63
France              477    198    263    1629           938             1.74
Netherlands         453    201    228    1560           882             1.77
Poland              384    225    283    1377           892             1.54
Belgium             382    184    290    1330           856             1.55
Romania             335    195    236    1200           766             1.57
Norway              328    199    348    1183           875             1.35
Switzerland         316    207    364    1155           887             1.30
Czechoslovakia      236    119    165     827           520             1.59
Cuba                139     90    168     507           397             1.28
Dutch East Indies     0      0      0       0             0              NaN

['Uruguay', 'Brazil', 'Sweden', 'Spain', 'Yugoslavia', 'Switzerland', 'Italy', 'England', 'Chile', 'United States', 'Paraguay', 'Mexico', 'Bolivia']

               wins  draws  loses  points  games_played  points_per_game
team
Brazil          672    219    171    2235          1062             2.10
England         625    261    207    2136          1093             1.95
Sweden          542    235    327    1861          1104             1.69
Mexico          515    233    258    1778          1006             1.77
Italy           477    243    173    1674           893             1.87
Spain           461    185    140    1568           786             1.99
Uruguay         428    243    302    1527           973             1.57
United States   352    163    278    1219           793             1.54
Switzerland     316    207    364    1155           887             1.30
Chile           316    179    340    1127           835             1.35
Paraguay        275    210    301    1035           786             1.32
Yugoslavia      223     98    162     767           483             1.59
Bolivia         119    119    296     476           534             0.89

['West Germany', 'Hungary', 'Austria', 'Uruguay', 'Switzerland', 'Brazil', 'England', 'Yugoslavia', 'Turkey', 'Italy', 'France', 'Belgium', 'Mexico', 'Czechoslovakia', 'Scotland', 'South Korea']

                wins  draws  loses  points  games_played  points_per_game
team
Brazil           672    219    171    2235          1062             2.10
England          625    261    207    2136          1093             1.95
South Korea      539    254    217    1871          1010             1.85
Mexico           515    233    258    1778          1006             1.77
Italy            477    243    173    1674           893             1.87
Hungary          472    222    312    1638          1006             1.63
France           477    198    263    1629           938             1.74
Uruguay          428    243    302    1527           973             1.57
Scotland         403    184    267    1393           854             1.63
Belgium          382    184    290    1330           856             1.55
Austria          367    187    309    1288           863             1.49
Switzerland      316    207    364    1155           887             1.30
Turkey           259    154    232     931           645             1.44
Czechoslovakia   236    119    165     827           520             1.59
Yugoslavia       223     98    162     767           483             1.59
West Germany       0      0      0       0             0              NaN

['Brazil', 'Sweden', 'France', 'West Germany', 'Wales', 'Soviet Union', 'Northern Ireland', 'Yugoslavia', 'Czechoslovakia', 'Hungary', 'England', 'Paraguay', 'Argentina', 'Scotland', 'Austria', 'Mexico']

                  wins  draws  loses  points  games_played  points_per_game
team
Brazil             672    219    171    2235          1062             2.10
England            625    261    207    2136          1093             1.95
Argentina          592    260    220    2036          1072             1.90
Sweden             542    235    327    1861          1104             1.69
Mexico             515    233    258    1778          1006             1.77
Hungary            472    222    312    1638          1006             1.63
France             477    198    263    1629           938             1.74
Scotland           403    184    267    1393           854             1.63
Austria            367    187    309    1288           863             1.49
Paraguay           275    210    301    1035           786             1.32
Wales              234    165    327     867           726             1.19
Czechoslovakia     236    119    165     827           520             1.59
Yugoslavia         223     98    162     767           483             1.59
Northern Ireland   185    160    362     715           707             1.01
Soviet Union         0      0      0       0             0              NaN
West Germany         0      0      0       0             0              NaN

['Brazil', 'Czechoslovakia', 'Chile', 'Yugoslavia', 'Hungary', 'Soviet Union', 'West Germany', 'England', 'Italy', 'Argentina', 'Mexico', 'Spain', 'Uruguay', 'Colombia', 'Bulgaria', 'Switzerland']

                wins  draws  loses  points  games_played  points_per_game
team
Brazil           672    219    171    2235          1062             2.10
England          625    261    207    2136          1093             1.95
Argentina        592    260    220    2036          1072             1.90
Mexico           515    233    258    1778          1006             1.77
Italy            477    243    173    1674           893             1.87
Hungary          472    222    312    1638          1006             1.63
Spain            461    185    140    1568           786             1.99
Uruguay          428    243    302    1527           973             1.57
Switzerland      316    207    364    1155           887             1.30
Chile            316    179    340    1127           835             1.35
Bulgaria         262    188    286     974           736             1.32
Colombia         258    179    204     953           641             1.49
Czechoslovakia   236    119    165     827           520             1.59
Yugoslavia       223     98    162     767           483             1.59
West Germany       0      0      0       0             0              NaN
Soviet Union       0      0      0       0             0              NaN

['England', 'West Germany', 'Portugal', 'Soviet Union', 'Argentina', 'Hungary', 'Uruguay', 'North Korea', 'Italy', 'Spain', 'Brazil', 'Mexico', 'Chile', 'France', 'Bulgaria', 'Switzerland']

              wins  draws  loses  points  games_played  points_per_game
team
Brazil         672    219    171    2235          1062             2.10
England        625    261    207    2136          1093             1.95
Argentina      592    260    220    2036          1072             1.90
Mexico         515    233    258    1778          1006             1.77
Italy          477    243    173    1674           893             1.87
Hungary        472    222    312    1638          1006             1.63
France         477    198    263    1629           938             1.74
Spain          461    185    140    1568           786             1.99
Uruguay        428    243    302    1527           973             1.57
Portugal       349    162    187    1209           698             1.73
Switzerland    316    207    364    1155           887             1.30
Chile          316    179    340    1127           835             1.35
Bulgaria       262    188    286     974           736             1.32
North Korea    162    106    122     592           390             1.52
West Germany     0      0      0       0             0              NaN
Soviet Union     0      0      0       0             0              NaN

['Brazil', 'Italy', 'West Germany', 'Uruguay', 'Soviet Union', 'Mexico', 'Peru', 'England', 'Sweden', 'Belgium', 'Romania', 'Israel*', 'Bulgaria**', 'Morocco', 'Czechoslovakia', 'El Salvador']

                wins  draws  loses  points  games_played  points_per_game
team
Brazil           672    219    171    2235          1062             2.10
England          625    261    207    2136          1093             1.95
Sweden           542    235    327    1861          1104             1.69
Mexico           515    233    258    1778          1006             1.77
Italy            477    243    173    1674           893             1.87
Uruguay          428    243    302    1527           973             1.57
Belgium          382    184    290    1330           856             1.55
Romania          335    195    236    1200           766             1.57
Morocco          306    175    139    1093           620             1.76
Peru             231    176    307     869           714             1.22
Czechoslovakia   236    119    165     827           520             1.59
El Salvador      200    138    276     738           614             1.20
Soviet Union       0      0      0       0             0              NaN
West Germany       0      0      0       0             0              NaN
Israel*            0      0      0       0             0              NaN
Bulgaria**         0      0      0       0             0              NaN

['West Germany', 'Netherlands', 'Poland', 'Brazil', 'Sweden', 'East Germany', 'Yugoslavia', 'Argentina', 'Scotland', 'Italy', 'Chile', 'Bulgaria', 'Uruguay', 'Australia', 'Haiti', 'Zaire']

              wins  draws  loses  points  games_played  points_per_game
team
Brazil         672    219    171    2235          1062             2.10
Argentina      592    260    220    2036          1072             1.90
Sweden         542    235    327    1861          1104             1.69
Italy          477    243    173    1674           893             1.87
Netherlands    453    201    228    1560           882             1.77
Uruguay        428    243    302    1527           973             1.57
Scotland       403    184    267    1393           854             1.63
Poland         384    225    283    1377           892             1.54
Chile          316    179    340    1127           835             1.35
Australia      297    125    162    1016           584             1.74
Bulgaria       262    188    286     974           736             1.32
Yugoslavia     223     98    162     767           483             1.59
Haiti          216    112    185     760           513             1.48
West Germany     0      0      0       0             0              NaN
East Germany     0      0      0       0             0              NaN
Zaire            0      0      0       0             0              NaN

['Argentina', 'Netherlands', 'Brazil', 'Italy', 'Poland', 'West Germany', 'Austria', 'Peru', 'Tunisia', 'Spain', 'Scotland', 'France', 'Sweden', 'Iran', 'Hungary', 'Mexico']

              wins  draws  loses  points  games_played  points_per_game
team
Brazil         672    219    171    2235          1062             2.10
Argentina      592    260    220    2036          1072             1.90
Sweden         542    235    327    1861          1104             1.69
Mexico         515    233    258    1778          1006             1.77
Italy          477    243    173    1674           893             1.87
Hungary        472    222    312    1638          1006             1.63
France         477    198    263    1629           938             1.74
Spain          461    185    140    1568           786             1.99
Netherlands    453    201    228    1560           882             1.77
Scotland       403    184    267    1393           854             1.63
Poland         384    225    283    1377           892             1.54
Austria        367    187    309    1288           863             1.49
Iran           349    147    119    1194           615             1.94
Tunisia        296    191    194    1079           681             1.58
Peru           231    176    307     869           714             1.22
West Germany     0      0      0       0             0              NaN

['Italy', 'West Germany', 'Poland', 'France', 'Brazil', 'England', 'Soviet Union', 'Austria', 'Northern Ireland', 'Belgium', 'Argentina', 'Spain', 'Algeria', 'Hungary', 'Scotland', 'Yugoslavia', 'Cameroon', 'Honduras', 'Czechoslovakia', 'Peru', 'Kuwait', 'Chile', 'New Zealand', 'El Salvador']

                  wins  draws  loses  points  games_played  points_per_game
team
Brazil             672    219    171    2235          1062             2.10
England            625    261    207    2136          1093             1.95
Argentina          592    260    220    2036          1072             1.90
Italy              477    243    173    1674           893             1.87
Hungary            472    222    312    1638          1006             1.63
France             477    198    263    1629           938             1.74
Spain              461    185    140    1568           786             1.99
Scotland           403    184    267    1393           854             1.63
Poland             384    225    283    1377           892             1.54
Belgium            382    184    290    1330           856             1.55
Austria            367    187    309    1288           863             1.49
Chile              316    179    340    1127           835             1.35
Kuwait             285    179    220    1034           684             1.51
Algeria            288    165    167    1029           620             1.66
Cameroon           271    192    153    1005           616             1.63
Honduras           247    161    212     902           620             1.45
Peru               231    176    307     869           714             1.22
Czechoslovakia     236    119    165     827           520             1.59
Yugoslavia         223     98    162     767           483             1.59
El Salvador        200    138    276     738           614             1.20
Northern Ireland   185    160    362     715           707             1.01
New Zealand        172     76    171     592           419             1.41
Soviet Union         0      0      0       0             0              NaN
West Germany         0      0      0       0             0              NaN

['Argentina', 'West Germany', 'France', 'Belgium', 'Brazil', 'Mexico', 'Spain', 'England', 'Denmark', 'Soviet Union', 'Morocco', 'Italy', 'Paraguay', 'Poland', 'Bulgaria', 'Uruguay', 'Portugal', 'Hungary', 'Scotland', 'South Korea', 'Northern Ireland', 'Algeria', 'Iraq', 'Canada']

                  wins  draws  loses  points  games_played  points_per_game
team
Brazil             672    219    171    2235          1062             2.10
England            625    261    207    2136          1093             1.95
Argentina          592    260    220    2036          1072             1.90
South Korea        539    254    217    1871          1010             1.85
Mexico             515    233    258    1778          1006             1.77
Italy              477    243    173    1674           893             1.87
Hungary            472    222    312    1638          1006             1.63
France             477    198    263    1629           938             1.74
Spain              461    185    140    1568           786             1.99
Uruguay            428    243    302    1527           973             1.57
Scotland           403    184    267    1393           854             1.63
Denmark            402    185    287    1391           874             1.59
Poland             384    225    283    1377           892             1.54
Belgium            382    184    290    1330           856             1.55
Portugal           349    162    187    1209           698             1.73
Iraq               304    191    163    1103           658             1.68
Morocco            306    175    139    1093           620             1.76
Paraguay           275    210    301    1035           786             1.32
Algeria            288    165    167    1029           620             1.66
Bulgaria           262    188    286     974           736             1.32
Northern Ireland   185    160    362     715           707             1.01
Canada             179    111    182     648           472             1.37
West Germany         0      0      0       0             0              NaN
Soviet Union         0      0      0       0             0              NaN

['West Germany', 'Argentina', 'Italy', 'England', 'Yugoslavia', 'Czechoslovakia', 'Cameroon', 'Republic of Ireland', 'Brazil', 'Spain', 'Belgium', 'Romania', 'Costa Rica', 'Colombia', 'Netherlands', 'Uruguay', 'Soviet Union', 'Austria', 'Scotland', 'Egypt', 'Sweden', 'South Korea', 'United States', 'United Arab Emirates']

,wins,draws,loses,points,games_played,points_per_game
team,,,,,,
Brazil,672,219,171,2235,1062,2.10
England,625,261,207,2136,1093,1.95
Argentina,592,260,220,2036,1072,1.90
South Korea,539,254,217,1871,1010,1.85
Sweden,542,235,327,1861,1104,1.69
Italy,477,243,173,1674,893,1.87
Spain,461,185,140,1568,786,1.99
Netherlands,453,201,228,1560,882,1.77
Uruguay,428,243,302,1527,973,1.57
Scotland,403,184,267,1393,854,1.63
Belgium,382,184,290,1330,856,1.55
Egypt,379,188,192,1325,759,1.75
Austria,367,187,309,1288,863,1.49
United States,352,163,278,1219,793,1.54
Romania,335,195,236,1200,766,1.57
Costa Rica,316,178,230,1126,724,1.56
Cameroon,271,192,153,1005,616,1.63
Colombia,258,179,204,953,641,1.49
Republic of Ireland,243,179,211,908,633,1.43
United Arab Emirates,246,152,214,890,612,1.45
Czechoslovakia,236,119,165,827,520,1.59
Yugoslavia,223,98,162,767,483,1.59
West Germany,0,0,0,0,0,NaN
Soviet Union,0,0,0,0,0,NaN

['Brazil', 'Italy', 'Sweden', 'Bulgaria', 'Germany', 'Romania', 'Netherlands', 'Spain', 'Nigeria', 'Argentina', 'Belgium', 'Saudi Arabia', 'Mexico', 'United States', 'Switzerland', 'Republic of Ireland', 'Norway', 'Russia', 'Colombia', 'South Korea', 'Bolivia', 'Cameroon', 'Morocco', 'Greece']

                     wins  draws  loses  points  games_played  points_per_game
team
Brazil                672    219    171    2235          1062             2.10
Argentina             592    260    220    2036          1072             1.90
Germany               600    215    219    2015          1034             1.95
South Korea           539    254    217    1871          1010             1.85
Sweden                542    235    327    1861          1104             1.69
Mexico                515    233    258    1778          1006             1.77
Italy                 477    243    173    1674           893             1.87
Spain                 461    185    140    1568           786             1.99
Netherlands           453    201    228    1560           882             1.77
Russia                385    197    167    1352           749             1.81
Belgium               382    184    290    1330           856             1.55
Saudi Arabia          351    173    220    1226           744             1.65
United States         352    163    278    1219           793             1.54
Romania               335    195    236    1200           766             1.57
Norway                328    199    348    1183           875             1.35
Switzerland           316    207    364    1155           887             1.30
Nigeria               311    192    158    1125           661             1.70
Morocco               306    175    139    1093           620             1.76
Cameroon              271    192    153    1005           616             1.63
Bulgaria              262    188    286     974           736             1.32
Colombia              258    179    204     953           641             1.49
Republic of Ireland   243    179    211     908           633             1.43
Greece                240    155    238     875           633             1.38
Bolivia               119    119    296     476           534             0.89

['France', 'Brazil', 'Croatia', 'Netherlands', 'Italy', 'Argentina', 'Germany', 'Denmark', 'England', 'FR Yugoslavia', 'Romania', 'Nigeria', 'Mexico', 'Paraguay', 'Norway', 'Chile', 'Spain', 'Morocco', 'Belgium', 'Iran', 'Colombia', 'Jamaica', 'Austria', 'South Africa', 'Cameroon', 'Tunisia', 'Scotland', 'Saudi Arabia', 'Bulgaria', 'South Korea', 'Japan', 'United States']

               wins  draws  loses  points  games_played  points_per_game
team
Brazil          672    219    171    2235          1062             2.10
England         625    261    207    2136          1093             1.95
Argentina       592    260    220    2036          1072             1.90
Germany         600    215    219    2015          1034             1.95
South Korea     539    254    217    1871          1010             1.85
Mexico          515    233    258    1778          1006             1.77
Italy           477    243    173    1674           893             1.87
France          477    198    263    1629           938             1.74
Spain           461    185    140    1568           786             1.99
Netherlands     453    201    228    1560           882             1.77
Scotland        403    184    267    1393           854             1.63
Denmark         402    185    287    1391           874             1.59
Japan           390    168    235    1338           793             1.69
Belgium         382    184    290    1330           856             1.55
Austria         367    187    309    1288           863             1.49
Saudi Arabia    351    173    220    1226           744             1.65
United States   352    163    278    1219           793             1.54
Romania         335    195    236    1200           766             1.57
Iran            349    147    119    1194           615             1.94
Norway          328    199    348    1183           875             1.35
Chile           316    179    340    1127           835             1.35
Nigeria         311    192    158    1125           661             1.70
Morocco         306    175    139    1093           620             1.76
Tunisia         296    191    194    1079           681             1.58
Paraguay        275    210    301    1035           786             1.32
Cameroon        271    192    153    1005           616             1.63
Bulgaria        262    188    286     974           736             1.32
Colombia        258    179    204     953           641             1.49
Jamaica         258    154    251     928           663             1.40
South Africa    215    147    121     792           483             1.64
Croatia         209    107     83     734           399             1.84
FR Yugoslavia     0      0      0       0             0              NaN

['Brazil', 'Germany', 'Turkey', 'South Korea', 'Spain', 'England', 'Senegal', 'United States', 'Japan', 'Denmark', 'Mexico', 'Republic of Ireland', 'Sweden', 'Belgium', 'Italy', 'Paraguay', 'South Africa', 'Argentina', 'Costa Rica', 'Cameroon', 'Portugal', 'Russia', 'Croatia', 'Ecuador', 'Poland', 'Uruguay', 'Nigeria', 'France', 'Tunisia', 'Slovenia', 'China PR', 'Saudi Arabia']

                     wins  draws  loses  points  games_played  points_per_game
team
Brazil                672    219    171    2235          1062             2.10
England               625    261    207    2136          1093             1.95
Argentina             592    260    220    2036          1072             1.90
Germany               600    215    219    2015          1034             1.95
South Korea           539    254    217    1871          1010             1.85
Sweden                542    235    327    1861          1104             1.69
Mexico                515    233    258    1778          1006             1.77
Italy                 477    243    173    1674           893             1.87
France                477    198    263    1629           938             1.74
Spain                 461    185    140    1568           786             1.99
Uruguay               428    243    302    1527           973             1.57
Denmark               402    185    287    1391           874             1.59
Poland                384    225    283    1377           892             1.54
Russia                385    197    167    1352           749             1.81
Japan                 390    168    235    1338           793             1.69
Belgium               382    184    290    1330           856             1.55
Saudi Arabia          351    173    220    1226           744             1.65
United States         352    163    278    1219           793             1.54
Portugal              349    162    187    1209           698             1.73
Costa Rica            316    178    230    1126           724             1.56
Nigeria               311    192    158    1125           661             1.70
Tunisia               296    191    194    1079           681             1.58
Senegal               298    172    171    1066           641             1.66
Paraguay              275    210    301    1035           786             1.32
Cameroon              271    192    153    1005           616             1.63
Turkey                259    154    232     931           645             1.44
Republic of Ireland   243    179    211     908           633             1.43
South Africa          215    147    121     792           483             1.64
Croatia               209    107     83     734           399             1.84
Ecuador               183    159    252     708           594             1.19
Slovenia              114     86    117     428           317             1.35
China PR                0      0      0       0             0              NaN

['Italy', 'France', 'Germany', 'Portugal', 'Brazil', 'Argentina', 'England', 'Ukraine', 'Spain', 'Switzerland', 'Netherlands', 'Ecuador', 'Ghana', 'Sweden', 'Mexico', 'Australia', 'South Korea', 'Paraguay', 'Ivory Coast', 'Czech Republic', 'Poland', 'Croatia', 'Angola', 'Tunisia', 'Iran', 'United States', 'Trinidad and Tobago', 'Japan', 'Saudi Arabia', 'Togo', 'Costa Rica', 'Serbia and Montenegro']

,wins,draws,loses,points,games_played,points_per_game
team,,,,,,
Brazil,672,219,171,2235,1062,2.10
England,625,261,207,2136,1093,1.95
Argentina,592,260,220,2036,1072,1.90
Germany,600,215,219,2015,1034,1.95
South Korea,539,254,217,1871,1010,1.85
Sweden,542,235,327,1861,1104,1.69
Mexico,515,233,258,1778,1006,1.77
Italy,477,243,173,1674,893,1.87
France,477,198,263,1629,938,1.74
Spain,461,185,140,1568,786,1.99
Netherlands,453,201,228,1560,882,1.77
Poland,384,225,283,1377,892,1.54
Japan,390,168,235,1338,793,1.69
Saudi Arabia,351,173,220,1226,744,1.65
United States,352,163,278,1219,793,1.54
Portugal,349,162,187,1209,698,1.73
Iran,349,147,119,1194,615,1.94
Switzerland,316,207,364,1155,887,1.30
Ivory Coast,326,164,149,1142,639,1.79
Trinidad and Tobago,321,164,268,1127,753,1.50
Costa Rica,316,178,230,1126,724,1.56
Ghana,311,178,185,1111,674,1.65
Tunisia,296,191,194,1079,681,1.58
Paraguay,275,210,301,1035,786,1.32
Australia,297,125,162,1016,584,1.74
Croatia,209,107,83,734,399,1.84
Ecuador,183,159,252,708,594,1.19
Czech Republic,191,74,98,647,363,1.78
Angola,141,148,126,571,415,1.38
Ukraine,152,94,92,550,338,1.63
Togo,141,114,192,537,447,1.20
Serbia and Montenegro,0,0,0,0,0,NaN

['Spain', 'Netherlands', 'Germany', 'Uruguay', 'Argentina', 'Brazil', 'Ghana', 'Paraguay', 'Japan', 'Chile', 'Portugal', 'United States', 'England', 'Mexico', 'South Korea', 'Slovakia', 'Ivory Coast', 'Slovenia', 'Switzerland', 'South Africa', 'Australia', 'New Zealand', 'Serbia', 'Denmark', 'Greece', 'Italy', 'Nigeria', 'Algeria', 'France', 'Honduras', 'Cameroon', 'North Korea']

               wins  draws  loses  points  games_played  points_per_game
team
Brazil          672    219    171    2235          1062             2.10
England         625    261    207    2136          1093             1.95
Argentina       592    260    220    2036          1072             1.90
Germany         600    215    219    2015          1034             1.95
South Korea     539    254    217    1871          1010             1.85
Mexico          515    233    258    1778          1006             1.77
Italy           477    243    173    1674           893             1.87
France          477    198    263    1629           938             1.74
Spain           461    185    140    1568           786             1.99
Netherlands     453    201    228    1560           882             1.77
Uruguay         428    243    302    1527           973             1.57
Denmark         402    185    287    1391           874             1.59
Japan           390    168    235    1338           793             1.69
United States   352    163    278    1219           793             1.54
Portugal        349    162    187    1209           698             1.73
Switzerland     316    207    364    1155           887             1.30
Ivory Coast     326    164    149    1142           639             1.79
Chile           316    179    340    1127           835             1.35
Nigeria         311    192    158    1125           661             1.70
Ghana           311    178    185    1111           674             1.65
Paraguay        275    210    301    1035           786             1.32
Algeria         288    165    167    1029           620             1.66
Australia       297    125    162    1016           584             1.74
Cameroon        271    192    153    1005           616             1.63
Honduras        247    161    212     902           620             1.45
Greece          240    155    238     875           633             1.38
South Africa    215    147    121     792           483             1.64
New Zealand     172     76    171     592           419             1.41
North Korea     162    106    122     592           390             1.52
Serbia          155     89    104     554           348             1.59
Slovakia        149     86    132     533           367             1.45
Slovenia        114     86    117     428           317             1.35

['Germany', 'Argentina', 'Netherlands', 'Brazil', 'Colombia', 'Belgium', 'France', 'Costa Rica', 'Chile', 'Mexico', 'Switzerland', 'Uruguay', 'Greece', 'Algeria', 'United States', 'Nigeria', 'Ecuador', 'Portugal', 'Croatia', 'Bosnia and Herzegovina', 'Ivory Coast', 'Italy', 'Spain', 'Russia', 'Ghana', 'England', 'South Korea', 'Iran', 'Japan', 'Australia', 'Honduras', 'Cameroon']

,wins,draws,loses,points,games_played,points_per_game
team,,,,,,
Brazil,672,219,171,2235,1062,2.10
England,625,261,207,2136,1093,1.95
Argentina,592,260,220,2036,1072,1.90
Germany,600,215,219,2015,1034,1.95
South Korea,539,254,217,1871,1010,1.85
Mexico,515,233,258,1778,1006,1.77
Italy,477,243,173,1674,893,1.87
France,477,198,263,1629,938,1.74
Spain,461,185,140,1568,786,1.99
Netherlands,453,201,228,1560,882,1.77
Uruguay,428,243,302,1527,973,1.57
Russia,385,197,167,1352,749,1.81
Japan,390,168,235,1338,793,1.69
Belgium,382,184,290,1330,856,1.55
United States,352,163,278,1219,793,1.54
Portugal,349,162,187,1209,698,1.73
Iran,349,147,119,1194,615,1.94
Switzerland,316,207,364,1155,887,1.30
Ivory Coast,326,164,149,1142,639,1.79
Chile,316,179,340,1127,835,1.35
Costa Rica,316,178,230,1126,724,1.56
Nigeria,311,192,158,1125,661,1.70
Ghana,311,178,185,1111,674,1.65
Algeria,288,165,167,1029,620,1.66
Australia,297,125,162,1016,584,1.74
Cameroon,271,192,153,1005,616,1.63
Colombia,258,179,204,953,641,1.49
Honduras,247,161,212,902,620,1.45
Greece,240,155,238,875,633,1.38
Croatia,209,107,83,734,399,1.84
Ecuador,183,159,252,708,594,1.19
Bosnia and Herzegovina,104,70,112,382,286,1.34

['France', 'Croatia', 'Belgium', 'England', 'Uruguay', 'Brazil', 'Sweden', 'Russia', 'Colombia', 'Mexico', 'Denmark', 'Spain', 'Portugal', 'Switzerland', 'Argentina', 'Japan', 'Iran', 'Senegal', 'Germany', 'Nigeria', 'Peru', 'Poland', 'Saudi Arabia', 'Serbia', 'South Korea', 'Tunisia', 'Australia', 'Costa Rica', 'Iceland', 'Morocco', 'Egypt', 'Panama']

              wins  draws  loses  points  games_played  points_per_game
team
Brazil         672    219    171    2235          1062             2.10
England        625    261    207    2136          1093             1.95
Argentina      592    260    220    2036          1072             1.90
Germany        600    215    219    2015          1034             1.95
South Korea    539    254    217    1871          1010             1.85
Sweden         542    235    327    1861          1104             1.69
Mexico         515    233    258    1778          1006             1.77
France         477    198    263    1629           938             1.74
Spain          461    185    140    1568           786             1.99
Uruguay        428    243    302    1527           973             1.57
Denmark        402    185    287    1391           874             1.59
Poland         384    225    283    1377           892             1.54
Russia         385    197    167    1352           749             1.81
Japan          390    168    235    1338           793             1.69
Belgium        382    184    290    1330           856             1.55
Egypt          379    188    192    1325           759             1.75
Saudi Arabia   351    173    220    1226           744             1.65
Portugal       349    162    187    1209           698             1.73
Iran           349    147    119    1194           615             1.94
Switzerland    316    207    364    1155           887             1.30
Costa Rica     316    178    230    1126           724             1.56
Nigeria        311    192    158    1125           661             1.70
Morocco        306    175    139    1093           620             1.76
Tunisia        296    191    194    1079           681             1.58
Senegal        298    172    171    1066           641             1.66
Australia      297    125    162    1016           584             1.74
Colombia       258    179    204     953           641             1.49
Peru           231    176    307     869           714             1.22
Croatia        209    107     83     734           399             1.84
Panama         183    136    223     685           542             1.26
Iceland        159    102    261     579           522             1.11
Serbia         155     89    104     554           348             1.59

['Argentina', 'France', 'Croatia', 'Morocco', 'England', 'Netherlands', 'Portugal', 'Brazil', 'Japan', 'Senegal', 'Australia', 'Switzerland', 'United States', 'Spain', 'Poland', 'South Korea', 'Germany', 'Ecuador', 'Cameroon', 'Uruguay', 'Tunisia', 'Mexico', 'Belgium', 'Ghana', 'Saudi Arabia', 'Iran', 'Costa Rica', 'Denmark', 'Serbia', 'Wales', 'Canada', 'Qatar']

               wins  draws  loses  points  games_played  points_per_game
team
Brazil          672    219    171    2235          1062             2.10
England         625    261    207    2136          1093             1.95
Argentina       592    260    220    2036          1072             1.90
Germany         600    215    219    2015          1034             1.95
South Korea     539    254    217    1871          1010             1.85
Mexico          515    233    258    1778          1006             1.77
France          477    198    263    1629           938             1.74
Spain           461    185    140    1568           786             1.99
Netherlands     453    201    228    1560           882             1.77
Uruguay         428    243    302    1527           973             1.57
Denmark         402    185    287    1391           874             1.59
Poland          384    225    283    1377           892             1.54
Japan           390    168    235    1338           793             1.69
Belgium         382    184    290    1330           856             1.55
Saudi Arabia    351    173    220    1226           744             1.65
United States   352    163    278    1219           793             1.54
Portugal        349    162    187    1209           698             1.73
Iran            349    147    119    1194           615             1.94
Switzerland     316    207    364    1155           887             1.30
Costa Rica      316    178    230    1126           724             1.56
Ghana           311    178    185    1111           674             1.65
Morocco         306    175    139    1093           620             1.76
Tunisia         296    191    194    1079           681             1.58
Senegal         298    172    171    1066           641             1.66
Australia       297    125    162    1016           584             1.74
Cameroon        271    192    153    1005           616             1.63
Qatar           260    158    220     938           638             1.47
Wales           234    165    327     867           726             1.19
Croatia         209    107     83     734           399             1.84
Ecuador         183    159    252     708           594             1.19
Canada          179    111    182     648           472             1.37
Serbia          155     89    104     554           348             1.59